# -*- coding: utf-8 -*-
"""GoogleColab - Basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FCDSKhclR9ReoGjrZ5etVx8B1K0QtbYy

System Specifiaction
"""

! cat /proc/cpuinfo

! cat /proc/meminfo

"""Installing Libraries"""

! pip install pandas

import pandas as pd

print ('Machine Learning')

! ls

s